# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/Vivadoprojects/mips32multi/mips32multi.cache/wt [current_project]
set_property parent.project_path F:/Vivadoprojects/mips32multi/mips32multi.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
read_mem F:/Vivadoprojects/mips32multi/mips32multi.sim/sim_1/behav/instructions.mem
read_verilog -library xil_defaultlib {
  F:/Vivadoprojects/mips32multi/mips32multi.srcs/sources_1/new/datapath.v
  F:/Vivadoprojects/mips32multi/mips32multi.srcs/sources_1/new/control.v
  F:/Vivadoprojects/mips32multi/mips32multi.srcs/sources_1/new/alucontrol.v
  F:/Vivadoprojects/mips32multi/mips32multi.srcs/sources_1/new/mips.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top mips -part xc7z010clg400-1


write_checkpoint -force -noxdef mips.dcp

catch { report_utilization -file mips_utilization_synth.rpt -pb mips_utilization_synth.pb }
